import type { DriftReport } from '../types';

const SEVERITY_EMOJI: Record<string, string> = {
  breaking: '🔴',
  warning: '🟡',
  safe: '🟢',
  info: 'ℹ️',
};

export function exportAsMarkdown(report: DriftReport): string {
  const lines: string[] = [
    `# Schema Drift Report`,
    `**Schema Type:** ${report.schemaType}`,
    `**Generated:** ${new Date().toLocaleString()}`,
    '',
    `## Summary`,
    report.summary,
    '',
    `| Severity | Count |`,
    `|----------|-------|`,
    `| 🔴 Breaking | ${report.breakingCount} |`,
    `| 🟡 Warning  | ${report.warningCount} |`,
    `| 🟢 Safe     | ${report.safeCount} |`,
    '',
  ];

  if (report.migrationNote) {
    lines.push(`## Migration Strategy`, report.migrationNote, '');
  }

  lines.push(`## Drift Details`);
  report.drifts.forEach((d, i) => {
    lines.push(
      '',
      `### ${i + 1}. \`${d.field}\` — ${d.changeType} ${SEVERITY_EMOJI[d.severity]}`,
      `- **Before:** \`${d.oldValue}\``,
      `- **After:** \`${d.newValue}\``,
      `- **Why it matters:** ${d.whyItMatters}`,
      `- **How to fix:** ${d.howToFix}`,
    );
  });

  lines.push('', '---', '_Generated by [Schema Drift Explainer](https://neha-rani-r.github.io/schema-drift-explainer) · DataForge Series by Neha Rani_');

  return lines.join('\n');
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}
